- name: Copy Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: Check is Prometheus up or not
  ansible.builtin.wait_for:
    port: 9090
    delay: 10
    timeout: 15