- name: Add Application user
  ansible.builtin.user:
    name: "{{app_user}}"

- name: Remove App Directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App Directory if it does not exist
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download and Unzip App content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /app
#    remote_src: yes

- name: Download and Unzip App content
  ansible.builtin.unarchive:
    src: http://172.31.37.60:8081/repository/{{component}}/{{component}}-{{ lookup('aws_ssm', '{{env}}.{{component}}.app_version', region='us-east-1' ) }}.zip
    dest: /app
    remote_src: yes