#- name: Install Maven
#  ansible.builtin.yum:
#    name: maven
#    state: installed

- name: Install Java
  ansible.builtin.yum:
    name: java-17-openjdk
    state: installed

- name: Include App Prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

## These steps are no more needed, As CI Pipeline is taking care of it now.
#- name: Install Maven Dependencies
#  ansible.builtin.shell: mvn clean package
#  args:
#    chdir: /app
#
#- name: Move {{component}} jar file
#  ansible.builtin.shell: mv target/{{component}}-1.0.jar {{component}}.jar
#  args:
#    chdir: /app

- name: Include Schema Setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include SystemD Service
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: Import Prometheus-node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

