- name: Copy {{component}} Service file
  ansible.builtin.template:
    src: catalogue.service
    dest: /etc/systemd/system/{{component}}.service

- name: Start {{component}}
  ansible.builtin.systemd_service:
    state: restarted
    name: {{component}}
    enabled: true
    daemon_reload: true
