groups:
  - name: CPUUtilization
    rules:
      - alert: HighCPUUtilization
        expr: 100 - (avg by (component, env, instance, job, name) (rate(node_cpu_seconds_total{mode="idle"}[1m]) * 100)) > 50
        for: 1m
        labels:
          severity: page
        annotations:
          summary: High CPU Usage

      - name: MemoryUtilization
        rules:
          - alert: HighMemoryUtilization
            expr: 100 - (100 * ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes)) > 50
            for: 1m
            labels:
              severity: page
            annotations:
              summary: High Memory Usage

          - name: ServerStatus
            rules:
              - alert: ServerStatus
                expr: up{job="ec2-nodes"} < 1
                for: 1m
                labels:
                  severity: page
                annotations:
                  summary: Server Status

          - name: ServiceStatus
            rules:
              {%- for component in labels %}

              - alert: ServiceStatus
                expr: node_systemd_unit_state{component={{ component.name }},  exported_name={{ component.service_name }}, state="active"} < 1
                for: 1m
                labels:
                  severity: page
                annotations:
                  summary: {{ component.name }} Component - Service Status
              {%- endfor %}